### ISSUE TITLE
@see {@link http://example.com|An Example} syntax

### ISSUE THREAD

**Issue by rapodaca** [esdoc/esdoc#216] opened 2016-02-10 00:14 UTC
JSDoc supports user-defined links in the <code>@see</code> tag:

``` javascript
/**
 * @see {@link http://example.com|An Example}
 */
const example = function () {

};
```

http://usejsdoc.org/tags-see.html

This is useful for presenting a human-readable description of the link, rather than a URL.

When I try this syntax, it shows up literally and isn't parsed. Is anchor text currently supported in the <code>@see</code> tag in ESDoc?

**Comment by h13i32maru** [comment] 2016-02-14 12:37
This issue is a duplicate of https://github.com/esdoc/esdoc/issues/212

**Comment by h13i32maru** [comment] 2016-12-31 08:53
Please check https://github.com/esdoc/esdoc/issues/367

**Closed by h13i32maru** 2016-12-31 08:53 UTC
Labels: Scope: Syntax, Status: Consider, Type: Feature
