### ISSUE TITLE
src at multiple location

### ISSUE THREAD

**Issue by navinSing** [esdoc/esdoc#210] opened 2016-01-27 08:46 UTC
hi, can we specify the src to be array at muliple location /

{
src :['./a/src','./b/src'],
dest: './d'
}

**Comment by raveclassic** [comment] 2016-01-28 11:37
@navinSing This is a duplicate of #72

**Comment by h13i32maru** [comment] 2016-02-14 12:19
Please see https://github.com/esdoc/esdoc/issues/72

**Closed by h13i32maru** 2016-02-14 12:19 UTC
Labels: Duplicate

**Comment by typhonrt** [comment] 2016-07-24 10:02
I have created a comprehensive solution for multiple source path support with backward compatibility and an overview is available in #310.
