### ISSUE TITLE
Alphabetical order + require = broken inheritance chain in docs

### ISSUE THREAD

**Issue by damirka** [esdoc/esdoc#302] opened 2016-06-24 10:32 UTC
Ok, it's not the regular use case of this generator (w/o `--harmony-modules`) but still.

**First case**:  A, Symbol (base)

``` JavaScript
// Path: app/Symbol.js
class Symbol {}
exports = Symbol;

// Path: app/A.js
const Symbol = require('app/Symbol');
class A extends Symbol {}
exports = A;
```

Docs output:

```
Class A
Extends: app/A.js~Symbol → A
```

---

**Second case**:  A, Symbol (base), Z

``` JavaScript
// Path: app/Symbol.js
class Symbol {}
exports = Symbol;

// Path: app/A.js
const Symbol = require('app/Symbol');
class A extends Symbol {}
exports = A;

// Path: app/Z.js
const Symbol = require('app/Symbol');
class Z extends Symbol {}
exports = Z;
```

Docs output:

```
Class A
Extends: app/A.js~Symbol → A

Class Z
Extends: app/A.js~Symbol → Z
```

---

**Third case**:  Symbol (base), Z

``` JavaScript
// Path: app/Symbol.js
class Symbol {}
exports = Symbol;

// Path: app/Z.js
const Symbol = require('app/Symbol');
class Z extends Symbol {}
exports = Z;
```

Docs output:

```
Class A
Extends: Symbol → A (correct)
```

If we remove `const aaa = require(bbb)` blocks, docs will work properly but the code won't.
I tried to use _@ignore_ tag with it but it didn't work.

_@extends_ tag also behaves oddly

``` JavaScript
/**
 * @extends app/Symbol.js~Symbol
 */
class A extends Symbol {}
// ...
```

Docs output:

```
Class A
Extends: * → A
```

Any ideas?

**Comment by typhonrt** [comment] 2016-06-28 07:49
ESDoc only currently supports ES6 / ES Module import / export semantics, so mixing CJS / ES6 won't be picked up out of the box. As far as I'm aware there are no ESDoc plugins to handle CJS use cases. In many ways this is a duplicate of #258.

**Comment by damirka** [comment] 2016-06-28 08:59
@typhonrt Improved *@ignore* tag could solve this case. I just don't get why it's not working with `require `and missing variables.

It's not a bug as I know this generator is for ES6 modules (which are still not supported even in NodeJS v6.2) but more a feature request to improve `@ignore` tag allowing people to cheat on the docs generation.

**Comment by typhonrt** [comment] 2016-06-28 17:18
> I just don't get why it's not working with requireand missing variables.

Well.. ESDoc ultimately is parsing ESTree generated AST from espree. Only various AST nodes are parsed and not all nodes per se for comments regarding `@ignore` tags. If you placed `@ignore` in front of the class declaration it would work and exclude that from documentation. Put `@ignore` randomly in other places it may not work as expected. IE it only ignores things that are actually parsed by ESDoc not a blanket ignore anything. 

A small consolation I suppose is that you can create pure ES6 Node / NPM modules with Babel and it works quite well. I have over 25 pure ES6+ based NPM modules publish now.

**Comment by damirka** [comment] 2016-06-28 17:28
Addition. I used `"undocumentIdentifier": false` flag and it works just fine sometimes except described case. I tried ignoring `require` calls, I tried leaving them without comments at all. 

Why is it forcing variable to be documented? I guess it's made for a case where parent class is not defined. But as you can see it's defined later in alphabetical order. I can only suggest building full tree after directory is scanned (at least).

**Comment by h13i32maru** [comment] 2016-12-31 07:02
I do not understand the problem. Please explain the new issue a bit easier to understand.

**Closed by h13i32maru** 2016-12-31 07:02 UTC
