### ISSUE TITLE
Destructing multiple parameters with default values causes parse error

### ISSUE THREAD

**Issue by arekkas** [esdoc/esdoc#303] opened 2016-07-01 19:24 UTC
This works:

``` js
/**
 * Dispatch when a cell hovers another item
 *
 * @param {object} drag
 * @param {object} hover
 * @param {number} level
 */
export const cellHover = ({ id: drag } = {}, { id: hover }, level = 0) => ({
  drag,
  hover,
  level
})

```

This throws an error (the second argument does not have a default value):

``` js
/**
 * Dispatch when a cell hovers another item
 *
 * @param {object} drag
 * @param {object} hover
 * @param {number} level
 */
export const cellHover = ({ id: drag } = {}, { id: hover } = {}, level = 0) => ({
  drag,
  hover,
  level
})
```

```
warning: could not parse the following code. if you want to use ES7, see esdoc-es7-plugin(https://github.com/esdoc/esdoc
-es7-plugin)
D:\workspace\js\editor\src\foo\doc.js
4|  * @param {object} hover
5|  * @param {number} level
6|  */
7| export const cellHover = ({ id: drag } = {}, { id: hover } = {}, level = 0) => ({
8|   drag,
9|   hover,
10|   level
```

**Comment by typhonrt** [comment] 2016-07-02 10:55
The reason being is that ES7 is not supported currently via the main ESDoc repo. It uses espree for AST generation w/ no support for ES6+.  I have a fork of ESDoc that uses Babylon w/ all plugins enabled that parses any ES6 / ES7 / edge JS. The example you listed above works with my fork:
https://github.com/typhonjs-node-esdoc/esdoc

I'm trying to get the maintainer of ESDoc to upstream my fork.

**Comment by arekkas** [comment] 2016-07-02 10:56
But that's valid ES6 syntax, no?

**Comment by typhonrt** [comment] 2016-07-02 11:16
Yep, you're right. So, it is because the espree version being used [is old / 2.2.0](https://github.com/esdoc/esdoc/blob/master/package.json#L26). It looks like there was an issue in espree `2.x` regarding [this problem](https://github.com/eslint/espree/issues/219) that was resolved in `3.x`.

**Comment by h13i32maru** [comment] 2016-12-31 06:31
@arekkas Thanks. I don't reproduce the error with latest ESDoc(v0.5). Please check it.

**Closed by h13i32maru** 2016-12-31 06:31 UTC
